#############################################################################
# Makefile for building: SudokuGUI
# Generated by qmake (2.01a) (Qt 4.8.5) on: Tue Jan 7 19:12:49 2014
# Project:  SudokuGUI.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile SudokuGUI.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Xlinker -zmuldefs -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MainWindow.cpp \
		SudokuMatrixWidget.cpp \
		Sudoku/SudokuMap.cpp \
		Sudoku/GroupExclusion.cpp \
		Sudoku/SudokuSolver.cpp \
		SudokuMatrixInput.cpp \
		InputWindow.cpp \
		SMatrixManipulator.cpp \
		OptionWindow.cpp \
		LogOutput.cpp moc_MainWindow.cpp \
		moc_SudokuMatrixWidget.cpp \
		moc_SudokuMatrixInput.cpp \
		moc_InputWindow.cpp \
		moc_SMatrixManipulator.cpp \
		moc_OptionWindow.cpp \
		moc_LogOutput.cpp
OBJECTS       = main.o \
		MainWindow.o \
		SudokuMatrixWidget.o \
		SudokuMap.o \
		GroupExclusion.o \
		SudokuSolver.o \
		SudokuMatrixInput.o \
		InputWindow.o \
		SMatrixManipulator.o \
		OptionWindow.o \
		LogOutput.o \
		moc_MainWindow.o \
		moc_SudokuMatrixWidget.o \
		moc_SudokuMatrixInput.o \
		moc_InputWindow.o \
		moc_SMatrixManipulator.o \
		moc_OptionWindow.o \
		moc_LogOutput.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		SudokuGUI.pro
QMAKE_TARGET  = SudokuGUI
DESTDIR       = 
TARGET        = SudokuGUI

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SudokuGUI.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile SudokuGUI.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile SudokuGUI.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SudokuGUI1.0.0 || $(MKDIR) .tmp/SudokuGUI1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SudokuGUI1.0.0/ && $(COPY_FILE) --parents MainWindow.h SudokuMatrixWidget.h Sudoku/SudokuMap.h Sudoku/Tools.h Sudoku/GroupExclusion.h Sudoku/SudokuSolver.h SudokuMatrixInput.h InputWindow.h SMatrixManipulator.h OptionWindow.h LogOutput.h qdebugstream.h .tmp/SudokuGUI1.0.0/ && $(COPY_FILE) --parents main.cpp MainWindow.cpp SudokuMatrixWidget.cpp Sudoku/SudokuMap.cpp Sudoku/GroupExclusion.cpp Sudoku/SudokuSolver.cpp SudokuMatrixInput.cpp InputWindow.cpp SMatrixManipulator.cpp OptionWindow.cpp LogOutput.cpp .tmp/SudokuGUI1.0.0/ && (cd `dirname .tmp/SudokuGUI1.0.0` && $(TAR) SudokuGUI1.0.0.tar SudokuGUI1.0.0 && $(COMPRESS) SudokuGUI1.0.0.tar) && $(MOVE) `dirname .tmp/SudokuGUI1.0.0`/SudokuGUI1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SudokuGUI1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MainWindow.cpp moc_SudokuMatrixWidget.cpp moc_SudokuMatrixInput.cpp moc_InputWindow.cpp moc_SMatrixManipulator.cpp moc_OptionWindow.cpp moc_LogOutput.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_SudokuMatrixWidget.cpp moc_SudokuMatrixInput.cpp moc_InputWindow.cpp moc_SMatrixManipulator.cpp moc_OptionWindow.cpp moc_LogOutput.cpp
moc_MainWindow.cpp: SMatrixManipulator.h \
		SudokuMatrixWidget.h \
		Sudoku/SudokuMap.h \
		Sudoku/Tools.h \
		Sudoku/GroupExclusion.h \
		Sudoku/SudokuSolver.h \
		InputWindow.h \
		SudokuMatrixInput.h \
		OptionWindow.h \
		LogOutput.h \
		qdebugstream.h \
		MainWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) MainWindow.h -o moc_MainWindow.cpp

moc_SudokuMatrixWidget.cpp: Sudoku/SudokuMap.h \
		Sudoku/Tools.h \
		Sudoku/GroupExclusion.h \
		Sudoku/SudokuSolver.h \
		SudokuMatrixWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) SudokuMatrixWidget.h -o moc_SudokuMatrixWidget.cpp

moc_SudokuMatrixInput.cpp: SudokuMatrixWidget.h \
		Sudoku/SudokuMap.h \
		Sudoku/Tools.h \
		Sudoku/GroupExclusion.h \
		Sudoku/SudokuSolver.h \
		SudokuMatrixInput.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) SudokuMatrixInput.h -o moc_SudokuMatrixInput.cpp

moc_InputWindow.cpp: SudokuMatrixInput.h \
		SudokuMatrixWidget.h \
		Sudoku/SudokuMap.h \
		Sudoku/Tools.h \
		Sudoku/GroupExclusion.h \
		Sudoku/SudokuSolver.h \
		InputWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) InputWindow.h -o moc_InputWindow.cpp

moc_SMatrixManipulator.cpp: SudokuMatrixWidget.h \
		Sudoku/SudokuMap.h \
		Sudoku/Tools.h \
		Sudoku/GroupExclusion.h \
		Sudoku/SudokuSolver.h \
		SMatrixManipulator.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) SMatrixManipulator.h -o moc_SMatrixManipulator.cpp

moc_OptionWindow.cpp: OptionWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) OptionWindow.h -o moc_OptionWindow.cpp

moc_LogOutput.cpp: qdebugstream.h \
		LogOutput.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) LogOutput.h -o moc_LogOutput.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp MainWindow.h \
		SMatrixManipulator.h \
		SudokuMatrixWidget.h \
		Sudoku/SudokuMap.h \
		Sudoku/Tools.h \
		Sudoku/GroupExclusion.h \
		Sudoku/SudokuSolver.h \
		InputWindow.h \
		SudokuMatrixInput.h \
		OptionWindow.h \
		LogOutput.h \
		qdebugstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		SMatrixManipulator.h \
		SudokuMatrixWidget.h \
		Sudoku/SudokuMap.h \
		Sudoku/Tools.h \
		Sudoku/GroupExclusion.h \
		Sudoku/SudokuSolver.h \
		InputWindow.h \
		SudokuMatrixInput.h \
		OptionWindow.h \
		LogOutput.h \
		qdebugstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

SudokuMatrixWidget.o: SudokuMatrixWidget.cpp SudokuMatrixWidget.h \
		Sudoku/SudokuMap.h \
		Sudoku/Tools.h \
		Sudoku/GroupExclusion.h \
		Sudoku/SudokuSolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SudokuMatrixWidget.o SudokuMatrixWidget.cpp

SudokuMap.o: Sudoku/SudokuMap.cpp Sudoku/SudokuMap.h \
		Sudoku/Tools.h \
		Sudoku/GroupExclusion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SudokuMap.o Sudoku/SudokuMap.cpp

GroupExclusion.o: Sudoku/GroupExclusion.cpp Sudoku/GroupExclusion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GroupExclusion.o Sudoku/GroupExclusion.cpp

SudokuSolver.o: Sudoku/SudokuSolver.cpp Sudoku/SudokuSolver.h \
		Sudoku/SudokuMap.h \
		Sudoku/Tools.h \
		Sudoku/GroupExclusion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SudokuSolver.o Sudoku/SudokuSolver.cpp

SudokuMatrixInput.o: SudokuMatrixInput.cpp SudokuMatrixInput.h \
		SudokuMatrixWidget.h \
		Sudoku/SudokuMap.h \
		Sudoku/Tools.h \
		Sudoku/GroupExclusion.h \
		Sudoku/SudokuSolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SudokuMatrixInput.o SudokuMatrixInput.cpp

InputWindow.o: InputWindow.cpp InputWindow.h \
		SudokuMatrixInput.h \
		SudokuMatrixWidget.h \
		Sudoku/SudokuMap.h \
		Sudoku/Tools.h \
		Sudoku/GroupExclusion.h \
		Sudoku/SudokuSolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InputWindow.o InputWindow.cpp

SMatrixManipulator.o: SMatrixManipulator.cpp SMatrixManipulator.h \
		SudokuMatrixWidget.h \
		Sudoku/SudokuMap.h \
		Sudoku/Tools.h \
		Sudoku/GroupExclusion.h \
		Sudoku/SudokuSolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SMatrixManipulator.o SMatrixManipulator.cpp

OptionWindow.o: OptionWindow.cpp OptionWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OptionWindow.o OptionWindow.cpp

LogOutput.o: LogOutput.cpp LogOutput.h \
		qdebugstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LogOutput.o LogOutput.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_SudokuMatrixWidget.o: moc_SudokuMatrixWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SudokuMatrixWidget.o moc_SudokuMatrixWidget.cpp

moc_SudokuMatrixInput.o: moc_SudokuMatrixInput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SudokuMatrixInput.o moc_SudokuMatrixInput.cpp

moc_InputWindow.o: moc_InputWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_InputWindow.o moc_InputWindow.cpp

moc_SMatrixManipulator.o: moc_SMatrixManipulator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SMatrixManipulator.o moc_SMatrixManipulator.cpp

moc_OptionWindow.o: moc_OptionWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OptionWindow.o moc_OptionWindow.cpp

moc_LogOutput.o: moc_LogOutput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LogOutput.o moc_LogOutput.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

